package templates

import (
	"fmt"

	"github.com/mates182/ginshot/models"
)

func GetDockerComposeTemplate(config *models.ProjectConfig) string {
	return fmt.Sprintf(`# auto-generated by ginshot
# Uncomment if needed
# version: '3.8'

services:
  # %s API Container
  %s:
    build: ..
    ports:
      - "%d:%d"
    container_name: %s
    environment:
      - GIN_MODE=release
    volumes:
      - .:/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge`, config.ProjectName, config.ProjectName, config.Port, config.Port, config.ProjectName)
}
