package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"

	"github.com/spf13/cobra"
)

// initCmd represents the init command
var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a new Gin project",
	Long: `Initialize a new Gin-based microservice with a structured project layout.
For example:

ginshot init my-service`,
	Args: cobra.MaximumNArgs(1), // Allows zero or one argument
	Run:  generateProject,
}

type InitConfig struct {
	Name          string
	Port          string
	Cors          bool
	Dockerfile    bool
	DockerCompose bool
	GitIgnore     bool
}

var port string

func init() {
	// Add the port flag to the init command
	initCmd.Flags().StringVarP(&port, "port", "p", "", "Port for the microservice (default is 8080)")

	rootCmd.AddCommand(initCmd)
}

// generateProject creates the project structure based on the provided name or asks for it
func generateProject(cmd *cobra.Command, args []string) {
	config := &InitConfig{
		Name:          "",
		Port:          port,
		Cors:          true,
		Dockerfile:    false,
		DockerCompose: false,
		GitIgnore:     true,
	}

	// Prompt for project name if it's not provided in the arguments
	if len(args) == 0 {
		fmt.Print(Bold + Cyan + "Project name " + Magenta + "(recomended format: lower-case-project-name) " + Grey + ">> " + Reset)
		fmt.Scanln(&config.Name)
	} else {
		config.Name = args[0]
	}

	// Validate the project name
	if regexp.MustCompile(`^[a-zA-Z][\da-zA-Z]*([-:\/\\_*+.\[\]{}()|"',;<>?]+[\da-zA-Z]+)*$`).FindString(config.Name) == "" {
		fmt.Println(Red + "Error: Project name cannot be empty, have blank spaces nor start with numbers or special characters" + Reset)
		return
	}

	// Ask for the port if not provided by the flag
	if config.Port == "" {
		fmt.Print(Bold + Cyan + "Port " + Magenta + "(default is 8080) " + Grey + ">> " + Reset)
		fmt.Scanln(&config.Port)
	}

	// Default to port 8080 if the user doesn't provide a port
	if regexp.MustCompile(`^[\d]{1,5}$`).FindString(config.Name) == "" {
		fmt.Println(Yellow + "Using default port: 8080" + Reset)
		config.Port = "8080"
	}

	// Create the project structure
	dir := fmt.Sprintf("./%s", config.Name)
	if err := createProjectDirectory(dir); err != nil {
		fmt.Println(err)
		return
	}

	// Create the necessary files
	if err := createMainFile(dir, config.Name, config.Port); err != nil {
		fmt.Println(err)
		return
	}

	if err := createRouterFile(dir, config.Name); err != nil {
		fmt.Println(err)
		return
	}

	// Set up the Go module
	if err := createGoMod(dir, config.Name); err != nil {
		fmt.Println(err)
		return
	}

	// Clean up Go modules
	if err := runGoModTidy(dir); err != nil {
		fmt.Println(err)
		return
	}

	// Successfully created the microservice
	fmt.Println(Bold + "Project '" + Cyan + config.Name + White + "' created " + Green + "successfully" + White + " in '" + Bold + Cyan + dir + White + "' on port " + Bold + Cyan + config.Port + Reset)
	// printProjectInstructions prints instructions for running the project

	fmt.Println(Bold + "\nTo run your project:" + Reset)
	fmt.Printf(Grey+"  cd %s\n", config.Name)
	fmt.Println("  go run main.go" + Reset)
	fmt.Println(Bold + "\nTest the API:" + Reset)
	fmt.Printf(Grey+"  curl http://localhost:%s/ping\n"+Reset, config.Port)
}

// createProjectDirectory creates the project directory
func createProjectDirectory(dir string) error {
	if err := os.MkdirAll(dir, os.ModePerm); err != nil {
		return fmt.Errorf("Error creating project directory: %v", err)
	}
	// Create the 'router' directory
	if err := os.MkdirAll(fmt.Sprintf("%s/router", dir), os.ModePerm); err != nil {
		return fmt.Errorf("Error creating router directory: %v", err)
	}
	return nil
}

// createMainFile creates the main.go file
func createMainFile(dir, name, port string) error {
	mainFile := fmt.Sprintf(`// auto-generated by ginshot
package main

import (
	"%s/router"
	"fmt"
)

func main() {
	fmt.Println("%s API started!")
	router := router.SetupRouter()
	router.Run("0.0.0.0:%s")
}
	`, name, name, port)

	if err := os.WriteFile(dir+"/main.go", []byte(mainFile), 0644); err != nil {
		return fmt.Errorf("Error creating main.go: %v", err)
	}
	return nil
}

// createRouterFile creates the router.go file
func createRouterFile(dir, name string) error {
	routerFile := fmt.Sprintf(`//auto-generated by ginshot
package router

import (
	"github.com/gin-gonic/gin"
)

func SetupRouter() *gin.Engine {
	r := gin.Default()

	// [HttpGET] Ping to %s API
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})

	return r
}
	`, name)

	if err := os.WriteFile(dir+"/router/router.go", []byte(routerFile), 0644); err != nil {
		return fmt.Errorf("Error creating router.go: %v", err)
	}
	return nil
}

// createGoMod initializes the Go module
func createGoMod(dir, name string) error {
	cmdGoMod := exec.Command("go", "mod", "init", name)
	cmdGoMod.Dir = dir
	if err := cmdGoMod.Run(); err != nil {
		return fmt.Errorf("Error creating go.mod: %v", err)
	}
	return nil
}

// runGoModTidy runs `go mod tidy` to clean up the dependencies
func runGoModTidy(dir string) error {
	cmdGoModTidy := exec.Command("go", "mod", "tidy")
	cmdGoModTidy.Dir = dir
	if err := cmdGoModTidy.Run(); err != nil {
		return fmt.Errorf("Error running go mod tidy: %v", err)
	}
	return nil
}
